# Datasource configuration
spring:
  datasource:
    url: jdbc:h2:mem:exploredb
    driverClassName: org.h2.Driver
    username: sa
    password:
    validation-query: SELECT 1;
    initial-size: 2
    sql-script-encoding: UTF-8

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create

  freemarker:
    cache: false